# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\天文爱好养成记\SunFlower\SunflowerGUI\sunflower\internal\view\window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 838)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("*{\n"
"font-size:14px;\n"
"font-family:sans-serif;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame{\n"
"background:#fdfdfd;\n"
"border-radius:6px;\n"
"color:#757575;\n"
"}\n"
"/*为输入框设置样式*/\n"
"QLineEdit{\n"
"border-radius:6px;\n"
"color:#rgb(0, 0, 0);\n"
"font-size:16px;\n"
"}\n"
"QLCDNumber{\n"
"border: 2px solid #707070;\n"
"background-color: rgb(79, 170, 170);\n"
"}\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(3, 169, 244);\n"
"    /*边框圆角半径为6像素*/ \n"
"    border-radius:6px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(750, 820))
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setStyleSheet("")
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.telescopeHALabel = QtWidgets.QLabel(self.groupBox)
        self.telescopeHALabel.setGeometry(QtCore.QRect(50, 230, 151, 21))
        self.telescopeHALabel.setObjectName("telescopeHALabel")
        self.telescopeDecLabel = QtWidgets.QLabel(self.groupBox)
        self.telescopeDecLabel.setGeometry(QtCore.QRect(300, 230, 151, 20))
        self.telescopeDecLabel.setObjectName("telescopeDecLabel")
        self.telescopeHALcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.telescopeHALcdNumber.setGeometry(QtCore.QRect(20, 260, 211, 51))
        self.telescopeHALcdNumber.setObjectName("telescopeHALcdNumber")
        self.telescopeDecLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.telescopeDecLcdNumber.setGeometry(QtCore.QRect(270, 260, 211, 51))
        self.telescopeDecLcdNumber.setObjectName("telescopeDecLcdNumber")
        self.statusLabel = QtWidgets.QLabel(self.groupBox)
        self.statusLabel.setGeometry(QtCore.QRect(330, 650, 111, 21))
        self.statusLabel.setObjectName("statusLabel")
        self.raLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.raLcdNumber.setGeometry(QtCore.QRect(520, 60, 211, 51))
        self.raLcdNumber.setObjectName("raLcdNumber")
        self.raLabel = QtWidgets.QLabel(self.groupBox)
        self.raLabel.setGeometry(QtCore.QRect(550, 30, 161, 21))
        self.raLabel.setObjectName("raLabel")
        self.moduleTabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.moduleTabWidget.setGeometry(QtCore.QRect(0, 410, 751, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.moduleTabWidget.sizePolicy().hasHeightForWidth())
        self.moduleTabWidget.setSizePolicy(sizePolicy)
        self.moduleTabWidget.setAccessibleName("")
        self.moduleTabWidget.setStyleSheet("border: 1px solid #b1b1b1;\n"
"")
        self.moduleTabWidget.setObjectName("moduleTabWidget")
        self.controlModuleTabWidget = QtWidgets.QWidget()
        self.controlModuleTabWidget.setObjectName("controlModuleTabWidget")
        self.recordButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.recordButton.setGeometry(QtCore.QRect(10, 80, 111, 41))
        self.recordButton.setObjectName("recordButton")
        self.resetButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.resetButton.setGeometry(QtCore.QRect(270, 80, 111, 41))
        self.resetButton.setObjectName("resetButton")
        self.traceButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.traceButton.setGeometry(QtCore.QRect(140, 20, 111, 41))
        self.traceButton.setObjectName("traceButton")
        self.positionButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.positionButton.setGeometry(QtCore.QRect(10, 20, 111, 41))
        self.positionButton.setObjectName("positionButton")
        self.stopButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.stopButton.setGeometry(QtCore.QRect(400, 80, 111, 41))
        self.stopButton.setObjectName("stopButton")
        self.correctButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.correctButton.setGeometry(QtCore.QRect(140, 80, 111, 41))
        self.correctButton.setObjectName("correctButton")
        self.powerButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.powerButton.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.powerButton.setObjectName("powerButton")
        self.comButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.comButton.setGeometry(QtCore.QRect(270, 140, 111, 41))
        self.comButton.setObjectName("comButton")
        self.comNumberSpinBox = QtWidgets.QSpinBox(self.controlModuleTabWidget)
        self.comNumberSpinBox.setGeometry(QtCore.QRect(400, 140, 111, 41))
        self.comNumberSpinBox.setStyleSheet("border: 2px solid #707070;")
        self.comNumberSpinBox.setMinimum(1)
        self.comNumberSpinBox.setMaximum(20)
        self.comNumberSpinBox.setProperty("value", 3)
        self.comNumberSpinBox.setObjectName("comNumberSpinBox")
        self.dropPowerButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.dropPowerButton.setGeometry(QtCore.QRect(140, 140, 111, 41))
        self.dropPowerButton.setObjectName("dropPowerButton")
        self.speedDescribeLabel = QtWidgets.QLabel(self.controlModuleTabWidget)
        self.speedDescribeLabel.setGeometry(QtCore.QRect(550, 0, 181, 21))
        self.speedDescribeLabel.setStyleSheet("")
        self.speedDescribeLabel.setObjectName("speedDescribeLabel")
        self.upButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.upButton.setGeometry(QtCore.QRect(610, 30, 50, 50))
        self.upButton.setObjectName("upButton")
        self.cwButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.cwButton.setGeometry(QtCore.QRect(550, 90, 50, 50))
        self.cwButton.setObjectName("cwButton")
        self.speedLabel = QtWidgets.QLabel(self.controlModuleTabWidget)
        self.speedLabel.setGeometry(QtCore.QRect(550, 150, 81, 41))
        self.speedLabel.setStyleSheet("")
        self.speedLabel.setObjectName("speedLabel")
        self.ccwButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.ccwButton.setGeometry(QtCore.QRect(670, 90, 50, 50))
        self.ccwButton.setObjectName("ccwButton")
        self.speedSpinBox = QtWidgets.QSpinBox(self.controlModuleTabWidget)
        self.speedSpinBox.setGeometry(QtCore.QRect(640, 150, 81, 41))
        self.speedSpinBox.setStyleSheet("border: 2px solid #707070;")
        self.speedSpinBox.setMinimum(1)
        self.speedSpinBox.setMaximum(3600)
        self.speedSpinBox.setProperty("value", 3600)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.downButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.downButton.setGeometry(QtCore.QRect(610, 90, 50, 51))
        self.downButton.setObjectName("downButton")
        self.moduleTabWidget.addTab(self.controlModuleTabWidget, "")
        self.starmapModuleTabWidget = QtWidgets.QWidget()
        self.starmapModuleTabWidget.setObjectName("starmapModuleTabWidget")
        self.addTargetButton = QtWidgets.QPushButton(self.starmapModuleTabWidget)
        self.addTargetButton.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.addTargetButton.setObjectName("addTargetButton")
        self.raLineEdit = QtWidgets.QLineEdit(self.starmapModuleTabWidget)
        self.raLineEdit.setGeometry(QtCore.QRect(170, 20, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raLineEdit.sizePolicy().hasHeightForWidth())
        self.raLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(-1)
        self.raLineEdit.setFont(font)
        self.raLineEdit.setText("")
        self.raLineEdit.setObjectName("raLineEdit")
        self.nameLineEdit = QtWidgets.QLineEdit(self.starmapModuleTabWidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(170, 140, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.DecLineEdit = QtWidgets.QLineEdit(self.starmapModuleTabWidget)
        self.DecLineEdit.setGeometry(QtCore.QRect(170, 80, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DecLineEdit.sizePolicy().hasHeightForWidth())
        self.DecLineEdit.setSizePolicy(sizePolicy)
        self.DecLineEdit.setText("")
        self.DecLineEdit.setObjectName("DecLineEdit")
        self.targetsListView = QtWidgets.QListView(self.starmapModuleTabWidget)
        self.targetsListView.setGeometry(QtCore.QRect(320, 10, 411, 181))
        self.targetsListView.setObjectName("targetsListView")
        self.delTargetButton = QtWidgets.QPushButton(self.starmapModuleTabWidget)
        self.delTargetButton.setGeometry(QtCore.QRect(20, 80, 131, 41))
        self.delTargetButton.setObjectName("delTargetButton")
        self.changeTargetButton = QtWidgets.QPushButton(self.starmapModuleTabWidget)
        self.changeTargetButton.setGeometry(QtCore.QRect(20, 140, 131, 41))
        self.changeTargetButton.setObjectName("changeTargetButton")
        self.moduleTabWidget.addTab(self.starmapModuleTabWidget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.moduleTabWidget.addTab(self.tab, "")
        self.decOffsetLabel = QtWidgets.QLabel(self.groupBox)
        self.decOffsetLabel.setGeometry(QtCore.QRect(330, 130, 101, 20))
        self.decOffsetLabel.setObjectName("decOffsetLabel")
        self.haOffsetLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.haOffsetLcdNumber.setGeometry(QtCore.QRect(20, 160, 211, 51))
        self.haOffsetLcdNumber.setObjectName("haOffsetLcdNumber")
        self.haOffsetLabel = QtWidgets.QLabel(self.groupBox)
        self.haOffsetLabel.setGeometry(QtCore.QRect(80, 130, 101, 21))
        self.haOffsetLabel.setObjectName("haOffsetLabel")
        self.decOffsetLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.decOffsetLcdNumber.setGeometry(QtCore.QRect(270, 160, 211, 51))
        self.decOffsetLcdNumber.setObjectName("decOffsetLcdNumber")
        self.utcLabel = QtWidgets.QLabel(self.groupBox)
        self.utcLabel.setGeometry(QtCore.QRect(100, 340, 41, 21))
        self.utcLabel.setObjectName("utcLabel")
        self.haLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.haLcdNumber.setGeometry(QtCore.QRect(20, 60, 211, 51))
        self.haLcdNumber.setObjectName("haLcdNumber")
        self.decLabel = QtWidgets.QLabel(self.groupBox)
        self.decLabel.setGeometry(QtCore.QRect(310, 30, 131, 20))
        self.decLabel.setObjectName("decLabel")
        self.haLabel = QtWidgets.QLabel(self.groupBox)
        self.haLabel.setGeometry(QtCore.QRect(60, 30, 121, 21))
        self.haLabel.setObjectName("haLabel")
        self.decLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.decLcdNumber.setGeometry(QtCore.QRect(270, 60, 211, 51))
        self.decLcdNumber.setObjectName("decLcdNumber")
        self.utcDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.utcDateTimeEdit.setEnabled(False)
        self.utcDateTimeEdit.setGeometry(QtCore.QRect(20, 370, 211, 22))
        self.utcDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.utcDateTimeEdit.setObjectName("utcDateTimeEdit")
        self.localtimeDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.localtimeDateTimeEdit.setEnabled(False)
        self.localtimeDateTimeEdit.setGeometry(QtCore.QRect(270, 370, 211, 22))
        self.localtimeDateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.localtimeDateTimeEdit.setObjectName("localtimeDateTimeEdit")
        self.localtimeLabel = QtWidgets.QLabel(self.groupBox)
        self.localtimeLabel.setGeometry(QtCore.QRect(340, 340, 91, 21))
        self.localtimeLabel.setObjectName("localtimeLabel")
        self.lstDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.lstDateTimeEdit.setEnabled(False)
        self.lstDateTimeEdit.setGeometry(QtCore.QRect(520, 370, 201, 22))
        self.lstDateTimeEdit.setKeyboardTracking(True)
        self.lstDateTimeEdit.setObjectName("lstDateTimeEdit")
        self.lstLabel = QtWidgets.QLabel(self.groupBox)
        self.lstLabel.setGeometry(QtCore.QRect(600, 340, 41, 21))
        self.lstLabel.setObjectName("lstLabel")
        self.statusTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.statusTextBrowser.setEnabled(True)
        self.statusTextBrowser.setGeometry(QtCore.QRect(0, 680, 751, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusTextBrowser.sizePolicy().hasHeightForWidth())
        self.statusTextBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(-1)
        self.statusTextBrowser.setFont(font)
        self.statusTextBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.statusTextBrowser.setMouseTracking(False)
        self.statusTextBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusTextBrowser.setAutoFillBackground(False)
        self.statusTextBrowser.setStyleSheet("border: 2px solid #707070;")
        self.statusTextBrowser.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.statusTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.statusTextBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.statusTextBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.statusTextBrowser.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.statusTextBrowser.setOverwriteMode(False)
        self.statusTextBrowser.setObjectName("statusTextBrowser")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(520, 150, 211, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.moduleTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setAccessibleName(_translate("Form", "UCAS 4.5M Telescope"))
        self.groupBox.setTitle(_translate("Form", "自动控制"))
        self.telescopeHALabel.setText(_translate("Form", "Telescope Hour Angle"))
        self.telescopeDecLabel.setText(_translate("Form", "Telescope Declination"))
        self.statusLabel.setText(_translate("Form", "Controler status"))
        self.raLabel.setText(_translate("Form", "Target Right Ascension"))
        self.recordButton.setText(_translate("Form", "记录误差"))
        self.resetButton.setText(_translate("Form", "指向天顶"))
        self.traceButton.setText(_translate("Form", "TRACE"))
        self.positionButton.setText(_translate("Form", "POSITION"))
        self.stopButton.setText(_translate("Form", "急停"))
        self.correctButton.setText(_translate("Form", "动态误差修正"))
        self.powerButton.setText(_translate("Form", "驱动上电"))
        self.comButton.setText(_translate("Form", "串口连接"))
        self.dropPowerButton.setText(_translate("Form", "驱动断电"))
        self.speedDescribeLabel.setText(_translate("Form", "误差修正数值之手动再修正"))
        self.upButton.setText(_translate("Form", "UP"))
        self.upButton.setShortcut(_translate("Form", "W"))
        self.cwButton.setText(_translate("Form", "CW"))
        self.cwButton.setShortcut(_translate("Form", "A"))
        self.speedLabel.setText(_translate("Form", "Speed/角秒"))
        self.ccwButton.setText(_translate("Form", "CCW"))
        self.ccwButton.setShortcut(_translate("Form", "D"))
        self.downButton.setText(_translate("Form", "DOWN"))
        self.downButton.setShortcut(_translate("Form", "S"))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.controlModuleTabWidget), _translate("Form", "Control"))
        self.addTargetButton.setText(_translate("Form", "ADD Target"))
        self.raLineEdit.setPlaceholderText(_translate("Form", "Right Ascension"))
        self.nameLineEdit.setPlaceholderText(_translate("Form", "target name"))
        self.DecLineEdit.setPlaceholderText(_translate("Form", "Declination"))
        self.delTargetButton.setText(_translate("Form", "DEL Target"))
        self.changeTargetButton.setText(_translate("Form", "Change Target"))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.starmapModuleTabWidget), _translate("Form", "Target"))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.tab), _translate("Form", "Correction"))
        self.decOffsetLabel.setText(_translate("Form", "DEC Offset"))
        self.haOffsetLabel.setText(_translate("Form", "HA Offset"))
        self.utcLabel.setText(_translate("Form", "UTC"))
        self.decLabel.setText(_translate("Form", "Target Declination"))
        self.haLabel.setText(_translate("Form", "Target Hour Angle"))
        self.utcDateTimeEdit.setDisplayFormat(_translate("Form", "yyyy/M/d H:mm:ss"))
        self.localtimeDateTimeEdit.setDisplayFormat(_translate("Form", "yyyy/M/d H:mm:ss"))
        self.localtimeLabel.setText(_translate("Form", "Local Time"))
        self.lstDateTimeEdit.setDisplayFormat(_translate("Form", "yyyy/M/d H:mm:ss"))
        self.lstLabel.setText(_translate("Form", "LST"))
        self.statusTextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'sans-serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:15px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><a name=\"taag_output_text\"></a><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\"> </span><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\"> _________             _____.__                              </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\"> /   _____/__ __  _____/ ____\\  |   ______  _  __ ___________ </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\"> \\_____  \\|  |  \\/    \\   __\\|  |  /  _ \\ \\/ \\/ // __ \\_  __ \\</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\"> /        \\  |  /   |  \\  |  |  |_(  &lt;_&gt; )     /\\  ___/|  | \\/</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\">/_______  /____/|___|  /__|  |____/\\____/ \\/\\_/  \\___  &gt;__|   </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'monospace\'; font-size:14px; color:#000000; background-color:#ffffff;\">        \\/           \\/                              \\/       0.1</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; color:#000000; background-color:#ffffff;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
