# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 711)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("*{\n"
"font-size:14px;\n"
"font-family:sans-serif;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame{\n"
"background:#fdfdfd;\n"
"border-radius:6px;\n"
"color:#757575;\n"
"}\n"
"/*为输入框设置样式*/\n"
"QLineEdit{\n"
"border-radius:6px;\n"
"color:#rgb(0, 0, 0);\n"
"font-size:16px;\n"
"}\n"
"QLCDNumber{\n"
"border: 2px solid #707070;\n"
"background-color: rgb(79, 170, 170);\n"
"}\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(3, 169, 244);\n"
"    /*边框圆角半径为6像素*/ \n"
"    border-radius:6px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(750, 680))
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setStyleSheet("")
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.telescopeHALabel = QtWidgets.QLabel(self.groupBox)
        self.telescopeHALabel.setGeometry(QtCore.QRect(50, 230, 151, 21))
        self.telescopeHALabel.setObjectName("telescopeHALabel")
        self.telescopeDecLabel = QtWidgets.QLabel(self.groupBox)
        self.telescopeDecLabel.setGeometry(QtCore.QRect(300, 230, 151, 20))
        self.telescopeDecLabel.setObjectName("telescopeDecLabel")
        self.telescopeHALcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.telescopeHALcdNumber.setGeometry(QtCore.QRect(20, 260, 211, 51))
        self.telescopeHALcdNumber.setObjectName("telescopeHALcdNumber")
        self.telescopeDecLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.telescopeDecLcdNumber.setGeometry(QtCore.QRect(270, 260, 211, 51))
        self.telescopeDecLcdNumber.setObjectName("telescopeDecLcdNumber")
        self.statusLabel = QtWidgets.QLabel(self.groupBox)
        self.statusLabel.setGeometry(QtCore.QRect(560, 130, 111, 21))
        self.statusLabel.setObjectName("statusLabel")
        self.raLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.raLcdNumber.setGeometry(QtCore.QRect(520, 60, 211, 51))
        self.raLcdNumber.setObjectName("raLcdNumber")
        self.raLabel = QtWidgets.QLabel(self.groupBox)
        self.raLabel.setGeometry(QtCore.QRect(550, 30, 161, 21))
        self.raLabel.setObjectName("raLabel")
        self.moduleTabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.moduleTabWidget.setGeometry(QtCore.QRect(0, 430, 751, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.moduleTabWidget.sizePolicy().hasHeightForWidth())
        self.moduleTabWidget.setSizePolicy(sizePolicy)
        self.moduleTabWidget.setAccessibleName("")
        self.moduleTabWidget.setStyleSheet("border: 1px solid #b1b1b1;\n"
"")
        self.moduleTabWidget.setObjectName("moduleTabWidget")
        self.controlModuleTabWidget = QtWidgets.QWidget()
        self.controlModuleTabWidget.setObjectName("controlModuleTabWidget")
        self.downButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.downButton.setGeometry(QtCore.QRect(620, 70, 50, 51))
        self.downButton.setObjectName("downButton")
        self.cwButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.cwButton.setGeometry(QtCore.QRect(560, 70, 50, 50))
        self.cwButton.setObjectName("cwButton")
        self.ccwButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.ccwButton.setGeometry(QtCore.QRect(680, 70, 50, 50))
        self.ccwButton.setObjectName("ccwButton")
        self.upButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.upButton.setGeometry(QtCore.QRect(620, 10, 50, 50))
        self.upButton.setObjectName("upButton")
        self.recordButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.recordButton.setGeometry(QtCore.QRect(10, 80, 111, 41))
        self.recordButton.setObjectName("recordButton")
        self.resetButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.resetButton.setGeometry(QtCore.QRect(140, 80, 111, 41))
        self.resetButton.setObjectName("resetButton")
        self.traceButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.traceButton.setGeometry(QtCore.QRect(140, 20, 111, 41))
        self.traceButton.setObjectName("traceButton")
        self.positionButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.positionButton.setGeometry(QtCore.QRect(10, 20, 111, 41))
        self.positionButton.setObjectName("positionButton")
        self.stopButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.stopButton.setGeometry(QtCore.QRect(270, 20, 111, 41))
        self.stopButton.setObjectName("stopButton")
        self.correctButton = QtWidgets.QPushButton(self.controlModuleTabWidget)
        self.correctButton.setGeometry(QtCore.QRect(270, 80, 111, 41))
        self.correctButton.setObjectName("correctButton")
        self.speedLabel = QtWidgets.QLabel(self.controlModuleTabWidget)
        self.speedLabel.setGeometry(QtCore.QRect(430, 20, 111, 41))
        self.speedLabel.setStyleSheet("")
        self.speedLabel.setObjectName("speedLabel")
        self.speedSpinBox = QtWidgets.QSpinBox(self.controlModuleTabWidget)
        self.speedSpinBox.setGeometry(QtCore.QRect(430, 80, 111, 41))
        self.speedSpinBox.setStyleSheet("border: 2px solid #707070;")
        self.speedSpinBox.setMaximum(4)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.moduleTabWidget.addTab(self.controlModuleTabWidget, "")
        self.starmapModuleTabWidget = QtWidgets.QWidget()
        self.starmapModuleTabWidget.setObjectName("starmapModuleTabWidget")
        self.addTargetButton = QtWidgets.QPushButton(self.starmapModuleTabWidget)
        self.addTargetButton.setGeometry(QtCore.QRect(20, 160, 131, 41))
        self.addTargetButton.setObjectName("addTargetButton")
        self.lineEdit = QtWidgets.QLineEdit(self.starmapModuleTabWidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.starmapModuleTabWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 110, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.starmapModuleTabWidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 60, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.targetLabel = QtWidgets.QLabel(self.starmapModuleTabWidget)
        self.targetLabel.setGeometry(QtCore.QRect(600, 10, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetLabel.sizePolicy().hasHeightForWidth())
        self.targetLabel.setSizePolicy(sizePolicy)
        self.targetLabel.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 0);")
        self.targetLabel.setObjectName("targetLabel")
        self.targetsListView = QtWidgets.QListView(self.starmapModuleTabWidget)
        self.targetsListView.setGeometry(QtCore.QRect(530, 40, 201, 161))
        self.targetsListView.setObjectName("targetsListView")
        self.moduleTabWidget.addTab(self.starmapModuleTabWidget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.moduleTabWidget.addTab(self.tab, "")
        self.decOffsetLabel = QtWidgets.QLabel(self.groupBox)
        self.decOffsetLabel.setGeometry(QtCore.QRect(330, 130, 101, 20))
        self.decOffsetLabel.setObjectName("decOffsetLabel")
        self.haOffsetLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.haOffsetLcdNumber.setGeometry(QtCore.QRect(20, 160, 211, 51))
        self.haOffsetLcdNumber.setObjectName("haOffsetLcdNumber")
        self.haOffsetLabel = QtWidgets.QLabel(self.groupBox)
        self.haOffsetLabel.setGeometry(QtCore.QRect(80, 130, 101, 21))
        self.haOffsetLabel.setObjectName("haOffsetLabel")
        self.decOffsetLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.decOffsetLcdNumber.setGeometry(QtCore.QRect(270, 160, 211, 51))
        self.decOffsetLcdNumber.setObjectName("decOffsetLcdNumber")
        self.utcLabel = QtWidgets.QLabel(self.groupBox)
        self.utcLabel.setGeometry(QtCore.QRect(100, 340, 41, 21))
        self.utcLabel.setObjectName("utcLabel")
        self.statusTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.statusTextBrowser.setEnabled(False)
        self.statusTextBrowser.setGeometry(QtCore.QRect(520, 160, 211, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusTextBrowser.sizePolicy().hasHeightForWidth())
        self.statusTextBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(-1)
        self.statusTextBrowser.setFont(font)
        self.statusTextBrowser.setMouseTracking(False)
        self.statusTextBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusTextBrowser.setAutoFillBackground(False)
        self.statusTextBrowser.setStyleSheet("color:#ff0000;\n"
"border: 2px solid #707070;")
        self.statusTextBrowser.setObjectName("statusTextBrowser")
        self.haLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.haLcdNumber.setGeometry(QtCore.QRect(20, 60, 211, 51))
        self.haLcdNumber.setObjectName("haLcdNumber")
        self.decLabel = QtWidgets.QLabel(self.groupBox)
        self.decLabel.setGeometry(QtCore.QRect(310, 30, 131, 20))
        self.decLabel.setObjectName("decLabel")
        self.haLabel = QtWidgets.QLabel(self.groupBox)
        self.haLabel.setGeometry(QtCore.QRect(60, 30, 121, 21))
        self.haLabel.setObjectName("haLabel")
        self.decLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.decLcdNumber.setGeometry(QtCore.QRect(270, 60, 211, 51))
        self.decLcdNumber.setObjectName("decLcdNumber")
        self.utcDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.utcDateTimeEdit.setEnabled(False)
        self.utcDateTimeEdit.setGeometry(QtCore.QRect(20, 370, 211, 22))
        self.utcDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.utcDateTimeEdit.setObjectName("utcDateTimeEdit")
        self.localtimeDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.localtimeDateTimeEdit.setEnabled(False)
        self.localtimeDateTimeEdit.setGeometry(QtCore.QRect(270, 370, 211, 22))
        self.localtimeDateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.localtimeDateTimeEdit.setObjectName("localtimeDateTimeEdit")
        self.localtimeLabel = QtWidgets.QLabel(self.groupBox)
        self.localtimeLabel.setGeometry(QtCore.QRect(340, 340, 91, 21))
        self.localtimeLabel.setObjectName("localtimeLabel")
        self.lstDateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.lstDateTimeEdit.setEnabled(False)
        self.lstDateTimeEdit.setGeometry(QtCore.QRect(520, 370, 201, 22))
        self.lstDateTimeEdit.setKeyboardTracking(True)
        self.lstDateTimeEdit.setObjectName("lstDateTimeEdit")
        self.lstLabel = QtWidgets.QLabel(self.groupBox)
        self.lstLabel.setGeometry(QtCore.QRect(600, 340, 41, 21))
        self.lstLabel.setObjectName("lstLabel")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.moduleTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setAccessibleName(_translate("Form", "UCAS 4.5M Telescope"))
        self.groupBox.setTitle(_translate("Form", "自动控制"))
        self.telescopeHALabel.setText(_translate("Form", "Telescope Hour Angle"))
        self.telescopeDecLabel.setText(_translate("Form", "Telescope Declination"))
        self.statusLabel.setText(_translate("Form", "Controler status"))
        self.raLabel.setText(_translate("Form", "Target Right Ascension"))
        self.downButton.setText(_translate("Form", "DOWN"))
        self.downButton.setShortcut(_translate("Form", "S"))
        self.cwButton.setText(_translate("Form", "CW"))
        self.cwButton.setShortcut(_translate("Form", "A"))
        self.ccwButton.setText(_translate("Form", "CCW"))
        self.ccwButton.setShortcut(_translate("Form", "D"))
        self.upButton.setText(_translate("Form", "UP"))
        self.upButton.setShortcut(_translate("Form", "W"))
        self.recordButton.setText(_translate("Form", "RECORD"))
        self.resetButton.setText(_translate("Form", "RESET"))
        self.traceButton.setText(_translate("Form", "TRACE"))
        self.positionButton.setText(_translate("Form", "POSITION"))
        self.stopButton.setText(_translate("Form", "STOP"))
        self.correctButton.setText(_translate("Form", "CORRECT"))
        self.speedLabel.setText(_translate("Form", "Speed Q⬆/E⬇"))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.controlModuleTabWidget), _translate("Form", "Control"))
        self.addTargetButton.setText(_translate("Form", "ADD Target"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Right Ascension"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "target name"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Declination"))
        self.targetLabel.setText(_translate("Form", "Targets"))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.starmapModuleTabWidget), _translate("Form", "Target"))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.tab), _translate("Form", "Correction"))
        self.decOffsetLabel.setText(_translate("Form", "DEC Offset"))
        self.haOffsetLabel.setText(_translate("Form", "HA Offset"))
        self.utcLabel.setText(_translate("Form", "UTC"))
        self.statusTextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'sans-serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Controler status</span></p></body></html>"))
        self.decLabel.setText(_translate("Form", "Target Declination"))
        self.haLabel.setText(_translate("Form", "Target Hour Angle"))
        self.utcDateTimeEdit.setDisplayFormat(_translate("Form", "yyyy/M/d H:mm:ss"))
        self.localtimeDateTimeEdit.setDisplayFormat(_translate("Form", "yyyy/M/d H:mm:ss"))
        self.localtimeLabel.setText(_translate("Form", "Local Time"))
        self.lstDateTimeEdit.setDisplayFormat(_translate("Form", "yyyy/M/d H:mm:ss"))
        self.lstLabel.setText(_translate("Form", "LST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
